name: terrihansonmead
favicon: null
layout_spectrum: 0.8374010368715972
typography_spectrum: 0.22944868030026555
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.14917382155545056
  lightness: 0.5968205442186445
  saturation: 0.6518532743211836
  rhythmicContrast: 0.843177298316732
purpose: []
